package shared;

public enum ExecutionState {
	LOGIN, //login screen
	VIEWING_TICTACTOE, VIEWING_CHECKERS,VIEWING_BATTLESHIP, //waitroom
	WAITING_TICTACTOE, WAITING_CHECKERS, WAITING_BATTLESHIP,
	PLAYTURN_TICTACTOE, PLAYWAIT_TICTACTOE, //playing
	PLAYTURN_CHECKERS, PLAYWAIT_CHECKERS,
	PLAYTURN_BATTLESHIP, PLAYWAIT_BATTLESHIP,
	WIN_TICTACTOE, LOSE_TICTACTOE, //Lose/win dialogue
	WIN_CHECKERS, LOSE_CHECKERS,
	WIN_BATTLESHIP, LOSE_BATTLESHIP
}
